name = "PrecisionCarriers"
uuid = "5b00bbae-6f32-4368-a198-a7942af0a543"
authors = ["Anton Reinhard <anton.reinhard@proton.me>"]
version = "0.2.1"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extensions]
DoubleFloatsExt = "DoubleFloats"
RandomExt = "Random"

[compat]
DoubleFloats = "1.4.3"
Printf = "1.10"
ProgressMeter = "1.10.4"
Random = "1.10"
Sobol = "1.5.0"
Statistics = "1.10"
Test = "1.10"
TestItemRunner = "1.1"
TestItems = "1.0.0"
julia = "1.10"

[extras]
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["Random", "DoubleFloats", "TestItems", "TestItemRunner", "Test"]
